import 'package:algolog/core/constants/app_assets.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../app_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_dimens.dart';
import '../../../core/constants/app_text_styles.dart';
import '../../../core/utils/date_formatter.dart';
import '../../../data/models/leave_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/leave_provider.dart';

class LeaveRequestScreen extends StatefulWidget {
  const LeaveRequestScreen({super.key});

  @override
  _LeaveRequestScreenState createState() => _LeaveRequestScreenState();
}

class _LeaveRequestScreenState extends State<LeaveRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();
  String? _selectedLeaveType;
  DateTime? _startDate;
  DateTime? _endDate;

  // TODO: Fetch leave types from API or use a predefined list
  final List<String> _leaveTypes = [
    "Sick Leave",
    "Casual Leave",
    "Unpaid Leave",
    "Vacation"
  ];

  Future<void> _selectDate(BuildContext context, bool isStartDate) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: (isStartDate ? _startDate : _endDate) ?? DateTime.now(),
      firstDate: DateTime.now().subtract(
          const Duration(days: 30)), // Can apply for past leaves? Adjust.
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null) {
      setState(() {
        if (isStartDate) {
          _startDate = picked;
          if (_endDate != null && _endDate!.isBefore(_startDate!)) {
            _endDate =
                _startDate; // Reset end date if it's before new start date
          }
        } else {
          _endDate = picked;
          if (_startDate != null && _endDate!.isBefore(_startDate!)) {
            _startDate =
                _endDate; // Reset start date if it's after new end date
          }
        }
      });
    }
  }

  Future<void> _submitLeaveRequest() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedLeaveType == null) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Please select leave type.")));
      return;
    }
    if (_startDate == null || _endDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Please select start and end dates.")));
      return;
    }

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final leaveProvider = Provider.of<LeaveProvider>(context, listen: false);

    final newLeave = LeaveRequestModel(
      id: '', // Will be generated by backend
      userId: authProvider.currentUser!.id,
      leaveType: _selectedLeaveType!,
      startDate: _startDate!,
      endDate: _endDate!,
      appliedDate: DateTime.now(), // Set by provider/repo
      status: LeaveStatus.pending, // Default status
      description: _descriptionController.text.trim(),
    );

    // TODO: API call for submitting leave request
    bool success = await leaveProvider.applyForLeave(newLeave);

    if (success && mounted) {
      // Show Process Complete / Leave request sent!
      Navigator.of(context).pop(); // Pop current screen
      _showLeaveSentConfirmation();
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: Text(leaveProvider.errorMessage ??
                "Failed to submit leave request.")),
      );
    }
  }

  void _showLeaveSentConfirmation() {
    showDialog(
        context: context,
        barrierDismissible: false,
        builder: (ctx) => AlertDialog(
              contentPadding: const EdgeInsets.all(AppDimens.paddingLarge),
              shape: RoundedRectangleBorder(
                  borderRadius:
                      BorderRadius.circular(AppDimens.borderRadiusMedium)),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Image.asset(AppAssets.checkmarkIcon,
                      height: 80, width: 80), // Assuming you have this
                  const SizedBox(height: AppDimens.paddingMedium),
                  const Text("Process Complete", style: AppTextStyles.heading2),
                  const SizedBox(height: AppDimens.paddingSmall),
                  Text(
                    "You have successfully sent your leave request.",
                    textAlign: TextAlign.center,
                    style: AppTextStyles.bodyTextMedium
                        .copyWith(color: AppColors.greyText),
                  ),
                  const SizedBox(height: AppDimens.paddingLarge),
                  ElevatedButton(
                    onPressed: () {
                      Navigator.of(ctx).pop(); // Close dialog
                    },
                    child: const Text("OK"),
                  )
                ],
              ),
            ));
  }

  @override
  Widget build(BuildContext context) {
    final leaveProvider = Provider.of<LeaveProvider>(context);
    return Scaffold(
      appBar: AppBar(title: const Text("Request Leave")),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppDimens.paddingMedium),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              DropdownButtonFormField<String>(
                decoration: const InputDecoration(labelText: "Leave Type"),
                value: _selectedLeaveType,
                hint: const Text("Select Leave Type"),
                items: _leaveTypes.map((type) {
                  return DropdownMenuItem(value: type, child: Text(type));
                }).toList(),
                onChanged: (value) =>
                    setState(() => _selectedLeaveType = value),
                validator: (value) =>
                    value == null ? "Please select leave type" : null,
              ),
              const SizedBox(height: AppDimens.paddingMedium),
              Row(
                children: [
                  Expanded(
                      child: _buildDateField("Start Date", _startDate,
                          () => _selectDate(context, true))),
                  const SizedBox(width: AppDimens.paddingMedium),
                  Expanded(
                      child: _buildDateField("End Date", _endDate,
                          () => _selectDate(context, false))),
                ],
              ),
              const SizedBox(height: AppDimens.paddingMedium),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: "Reason / Description (Optional)",
                  alignLabelWithHint: true,
                ),
                maxLines: 3,
                maxLength: 200,
              ),
              const SizedBox(height: AppDimens.paddingLarge),
              leaveProvider.isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        onPressed: _submitLeaveRequest,
                        child: const Text("Submit Request"),
                      ),
                    ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildDateField(
      String label, DateTime? selectedDate, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      child: InputDecorator(
        decoration: InputDecoration(
          labelText: label,
          // border: OutlineInputBorder(), // Use theme's default
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            Text(
              selectedDate != null
                  ? DateFormatter.formatToyMd(selectedDate)
                  : "Select",
              style: selectedDate != null
                  ? AppTextStyles.bodyTextMedium
                  : AppTextStyles.bodyTextMedium
                      .copyWith(color: AppColors.greyText),
            ),
            const Icon(Icons.calendar_today_outlined,
                color: AppColors.greyText),
          ],
        ),
      ),
    );
  }
}
